[project]
name = "2d-point-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.7"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "torch>=2.5.1",
]
